---
global:
  slack_api_url: ${SLACK_URL}
route:
  group_by: ['...']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'

  routes:
  # null route ssh space config in dev
  - receiver: "null"
    matchers:
    - alertname = "SSH Misconfiguration Detected"
    - env = "dev"

receivers:
  - name: "null"
  - name: 'web.hook'
    slack_configs:
      - channel: '#idva-alerts'
        title: |-
          {{ "${ENVIRONMENT_NAME}" | toUpper }} – {{ .CommonLabels.app }} – {{ .CommonLabels.alertname }}  {{ .CommonAnnotations.icon }}
        color: |-
          {{ if eq "${ENVIRONMENT_NAME}" "prod" }}#ff0000{{ else if eq "${ENVIRONMENT_NAME}" "test" }}#0000ff{{ else }}#000000{{ end }}
        text: |
          Summary: {{ .CommonAnnotations.summary }}
          {{ .CommonAnnotations.description }}
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
