{
 "title": "IDVA App Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App Name", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  { "title": "$app crash history", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$app crash history",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (app) (irate(crash{app=~\"$app\"}[5m]) * 60)",
     "legendFormat": "{{app}} crashes"
    }
   ]
  },
  { "title": "$app http traffic metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$app requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (app) (irate(requests{app=~\"$app\"}[5m]) * 60) # multiply by 60 for real time per second usage",
     "legendFormat": "requests to {{app}}"
    }
   ]
  },
  {
   "title": "$app http requests per second by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum by (status_range) (irate(requests{app=~\"$app\"}[5m]) * 60) # multiply by 60 for real time per second usage",
     "legendFormat": "{{status_range}}"
    }
   ]
  },
  {
   "title": "$app response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.99, rate(response_time_bucket{app=~\"$app\"}[5m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.95, rate(response_time_bucket{app=~\"$app\"}[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.9, rate(response_time_bucket{app=~\"$app\"}[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "avg by (app) (\n  rate(response_time_bucket{app=~\"$app\"}[5m])\n)"
    }
   ]
  },
  { "title": "$app specific hardware metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$app cpu utilization percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "quantile(0.99, cpu{app=~\"$app\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.95, cpu{app=~\"$app\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.5, cpu{app=~\"$app\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "avg by (app) (\n  cpu{app=~\"$app\"}\n)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$app cpu utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu{app=~\"$app\"}",
     "legendFormat": "instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "$app memory utilization percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "quantile(.99, memory_utilization{app=~\"$app\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(.95, memory_utilization{app=~\"$app\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(.50, memory_utilization{app=~\"$app\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "avg by (app) (\n  memory_utilization{app=~\"$app\"}\n)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$app memory utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "memory_utilization{app=~\"$app\"}",
     "legendFormat": "instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "$app storage utilization percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "quantile(.99, disk_utilization{app=~\"$app\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(.95, disk_utilization{app=~\"$app\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(.50, disk_utilization{app=~\"$app\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "avg by (app) (\n  disk_utilization{app=~\"$app\"}\n)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$app storage utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_utilization{app=~\"$app\"}",
     "legendFormat": "instance {{exported_instance}}"
    }
   ]
  }
 ]
}