{
 "title": "IDVA CF System Metrics",
 "description": "Live views into the hardware utilization for the IDVA system.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CF App Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CF App Crash History",
   "type": "status-history",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (app) (irate(crash[5m]) * 60)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Hardware Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (app) (\n  avg_over_time(cpu[5m])\n)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Real CPU Usage (no averages)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu",
     "legendFormat": "{{app}} instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (app) (\n  avg_over_time(memory_utilization[5m])\n)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (app) (\n  avg_over_time(disk_utilization[5m])\n)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}