---
name: Deploy Grafana

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'grafana/**'
      - '.github/workflows/deploy-grafana.yaml'
      - '!**.md'  # Ignore all markdown files in the repository
  release:
    types: [released]

jobs:
  deploy:
    if: github.repository_owner == 'GSA-TTS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: GSA-TTS/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}
          space-suffix: "-closed"

      - name: Install Grafana
        run: ./install_grafana.sh
        working-directory: ./grafana

      - name: Deploy Grafana
        run: cf push
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --var GRAFANA_PASS=${{ secrets.GRAFANA_PASS }}
          --strategy rolling
        working-directory: ./grafana

      - name: Apply CF Network Policies
        run: ./create-network-policies.sh
        env:
          ENVIRONMENT_NAME: ${{ steps.cf-setup.outputs.target-environment }}
